### ISSUE TITLE
Having trouble getting Generator to work in cc 2015 with panel-created generator.js prefs file present.

### ISSUE THREAD

**Issue by timothynoel** [adobe-photoshop/generator-panels#18]
Generator isn't working with either a debug install of latest panel or the one posted on the official site. Seems to be the presence/format of ~/generator.js, as Generator doesn't generate assets with that file present.  Not sure if its the way the panel is writing the file, or the way generator is reading it.

**Comment by isonno** [comment]
I was able to reproduce, but _only_ if Generator is started internally by PS.  If I start generator via the command line, it works fine.

**Comment by isonno** [comment]
Also tracked via Watson bug 4010097

**Comment by isonno** [comment]
The watson bug ([4010097](https://watsonexp.corp.adobe.com/#bug=4010097)) is marked as fixed, so I'm closing the issue.
