### ISSUE TITLE
ExtensionManifest attributes in manifest.xml must be on a single line

### ISSUE THREAD

**Issue by jkaving** [adobe-photoshop/generator-panels#27]
Found this project via the link in https://github.com/Adobe-CEP/CEP-Resources where the `installPanels.py` script is suggested as a way to install extensions.

The script works well for a custom extension, but fails if the attributes of the `ExtensionManifest` element in `manifest.xml` are not written in a single line.

This is currently no problem in this project, but it may cause unexpected errors in the future if someone reformats the XML in the `manifest.xml` files.

**Comment by isonno** [comment]
Thanks.  I'm out of the office until next week, but I'll review it when I get back.
