### ISSUE TITLE
Signing problem

### ISSUE THREAD

**Issue by sschoellhammer** [adobe-photoshop/generator-panels#32]
Hello there,

I think this might be less a of an "issue" than something with my setup.
When I run the python script to install the extensions and then click them in PS I get this message:

![image](https://user-images.githubusercontent.com/6559937/35232709-75774e12-ff9c-11e7-9945-4a0cd39dea14.png)

This also happens with my own attempts at creating extensions - I was hoping that you might have an idea what's wrong .. I was under the impression that I can use extensions without signing if they run on my own machine, is that not correct?

Thanks a lot in advance!
Seb

**Comment by sschoellhammer** [comment]
Got it ... 
On Mac, open the file ~/Library/Preferences/com.adobe.CSXS.4.plist and add a row with key PlayerDebugMode, of type String, and value 1.
On Windows, open the registry key HKEY_CURRENT_USER/Software/Adobe/CSXS.4 and add a key named PlayerDebugMode, of type String, and value 1.

And I guess, restart machine...

**Comment by isonno** [comment]
Right. The `installPanels.py` script does this for you; if you do:

  `  $ installPanels.py -d on`

the script sets up the appropriate plist file or registry key. You shouldn't need to reboot.
